### ISSUE TITLE
Bridge connection fails regularly, followed by 0-values

### ISSUE THREAD

**Issue by beniwohli** [michaelarnauts/comfoconnect#44]
Hi

I use comfoconnect via the home assistant integration. Looking at history graphs in home assistant, I realized that the values for all monitored sensors jumps to `0` regularly, about every 30 minutes:

![image](https://user-images.githubusercontent.com/93675/131623364-653e6393-fcea-44fd-a86b-32df07c6ffa9.png)

(the irregularities are from me trying to debug the issue).

After enabling DEBUG logging, this is what I see:

    2021-09-01 09:00:29 WARNING (Thread-4) [comfoconnect] THe connection was broken. We will try to reconnect later.
    2021-09-01 09:00:34 INFO (Thread-18) [comfoconnect] Unhandled CnNodeNotificationType
    2021-09-01 09:00:34 INFO (Thread-18) [comfoconnect] Unhandled CnNodeNotificationType
    2021-09-01 09:00:34 INFO (Thread-18) [comfoconnect] Unhandled CnNodeNotificationType
    2021-09-01 09:00:34 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 65: 0
    2021-09-01 09:00:34 DEBUG (SyncWorker_6) [homeassistant.components.comfoconnect.fan] Handle update for fan speed (65): 0
    2021-09-01 09:00:34 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 291: 0
    2021-09-01 09:00:34 DEBUG (SyncWorker_13) [homeassistant.components.comfoconnect.sensor] Handle update for sensor exhaust_humidity (291): 0
    2021-09-01 09:00:34 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 192: 0
    2021-09-01 09:00:34 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 290: 0
    2021-09-01 09:00:34 DEBUG (SyncWorker_8) [homeassistant.components.comfoconnect.sensor] Handle update for sensor days_to_replace_filter (192): 0
    2021-09-01 09:00:34 DEBUG (SyncWorker_8) [homeassistant.components.comfoconnect.sensor] Handle update for sensor current_humidity (290): 0
    2021-09-01 09:00:34 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 120: 0
    2021-09-01 09:00:34 DEBUG (SyncWorker_14) [homeassistant.components.comfoconnect.sensor] Handle update for sensor air_flow_supply (120): 0
    2021-09-01 09:00:34 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 274: 0
    2021-09-01 09:00:34 DEBUG (SyncWorker_4) [homeassistant.components.comfoconnect.sensor] Handle update for sensor current_temperature (274): 0
    2021-09-01 09:00:34 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 119: 0
    2021-09-01 09:00:34 DEBUG (SyncWorker_12) [homeassistant.components.comfoconnect.sensor] Handle update for sensor air_flow_exhaust (119): 0
    2021-09-01 09:00:34 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 275: 0
    2021-09-01 09:00:34 DEBUG (SyncWorker_1) [homeassistant.components.comfoconnect.sensor] Handle update for sensor exhaust_temperature (275): 0
    2021-09-01 09:00:34 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 128: 0
    2021-09-01 09:00:34 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 292: 0
    2021-09-01 09:00:34 DEBUG (SyncWorker_3) [homeassistant.components.comfoconnect.sensor] Handle update for sensor power_usage (128): 0
    2021-09-01 09:00:34 DEBUG (SyncWorker_6) [homeassistant.components.comfoconnect.sensor] Handle update for sensor outside_humidity (292): 0
    2021-09-01 09:00:34 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 130: 0
    2021-09-01 09:00:34 DEBUG (SyncWorker_13) [homeassistant.components.comfoconnect.sensor] Handle update for sensor power_total (130): 0
    2021-09-01 09:00:34 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 276: 0
    2021-09-01 09:00:34 DEBUG (SyncWorker_8) [homeassistant.components.comfoconnect.sensor] Handle update for sensor outside_temperature (276): 0
    2021-09-01 09:00:34 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 294: 0
    2021-09-01 09:00:34 DEBUG (SyncWorker_14) [homeassistant.components.comfoconnect.sensor] Handle update for sensor supply_humidity (294): 0
    2021-09-01 09:00:34 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 221: 0
    2021-09-01 09:00:34 DEBUG (SyncWorker_4) [homeassistant.components.comfoconnect.sensor] Handle update for sensor supply_temperature (221): 0
    2021-09-01 09:00:34 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 192: 43
    2021-09-01 09:00:35 DEBUG (SyncWorker_12) [homeassistant.components.comfoconnect.sensor] Handle update for sensor days_to_replace_filter (192): 43
    2021-09-01 09:00:35 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 290: 60
    2021-09-01 09:00:35 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 120: 152
    2021-09-01 09:00:35 DEBUG (SyncWorker_1) [homeassistant.components.comfoconnect.sensor] Handle update for sensor current_humidity (290): 60
    2021-09-01 09:00:35 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 119: 150
    2021-09-01 09:00:35 DEBUG (SyncWorker_1) [homeassistant.components.comfoconnect.sensor] Handle update for sensor air_flow_supply (120): 152
    2021-09-01 09:00:35 DEBUG (SyncWorker_1) [homeassistant.components.comfoconnect.sensor] Handle update for sensor air_flow_exhaust (119): 150
    2021-09-01 09:00:35 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 65: 2
    2021-09-01 09:00:35 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 291: 77
    2021-09-01 09:00:35 DEBUG (SyncWorker_3) [homeassistant.components.comfoconnect.fan] Handle update for fan speed (65): 2
    2021-09-01 09:00:35 DEBUG (SyncWorker_6) [homeassistant.components.comfoconnect.sensor] Handle update for sensor exhaust_humidity (291): 77
    2021-09-01 09:00:35 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 128: 51
    2021-09-01 09:00:35 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 292: 82
    2021-09-01 09:00:35 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 130: 181
    2021-09-01 09:00:35 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 294: 59
    2021-09-01 09:00:35 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 274: 223
    2021-09-01 09:00:35 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 275: 166
    2021-09-01 09:00:35 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 276: 152
    2021-09-01 09:00:35 DEBUG (SyncWorker_13) [homeassistant.components.comfoconnect.sensor] Handle update for sensor power_usage (128): 51
    2021-09-01 09:00:35 DEBUG (SyncWorker_7) [homeassistant.components.comfoconnect.sensor] Handle update for sensor outside_humidity (292): 82
    2021-09-01 09:00:35 DEBUG (SyncWorker_8) [homeassistant.components.comfoconnect.sensor] Handle update for sensor power_total (130): 181
    2021-09-01 09:00:35 DEBUG (SyncWorker_13) [homeassistant.components.comfoconnect.sensor] Handle update for sensor supply_humidity (294): 59
    2021-09-01 09:00:35 DEBUG (Thread-18) [homeassistant.components.comfoconnect] Received update for 221: 219
    2021-09-01 09:00:35 DEBUG (SyncWorker_9) [homeassistant.components.comfoconnect.sensor] Handle update for sensor current_temperature (274): 223
    2021-09-01 09:00:35 DEBUG (SyncWorker_8) [homeassistant.components.comfoconnect.sensor] Handle update for sensor exhaust_temperature (275): 166
    2021-09-01 09:00:35 DEBUG (SyncWorker_13) [homeassistant.components.comfoconnect.sensor] Handle update for sensor outside_temperature (276): 152
    2021-09-01 09:00:35 DEBUG (SyncWorker_7) [homeassistant.components.comfoconnect.sensor] Handle update for sensor supply_temperature (221): 219

It looks like after a connection error, the first bunch of values received by the bridge are `0`, and the actual values are sent right after.

This makes it difficult to implement e.g. automations on the `days_to_replace_filter` value. Also, the new energy dashboard in Home Assistant can't use `power_total` as the value isn't strictly monotonic (it would interpret every 0 value as a reset, then on the next update think that the device used X kWh instantly (X being the total number of kWhs used by the device).

Does anybody else see this behavior?

Trying to think of work arounds, the pycomfoconnect could dismiss the first received value for each sensor after a reconnect (or even only dismiss it if it is `0`). If that is an acceptable solution, I can open a PR.

**Comment by klaudiusz223** [comment]
I also noticed this behavior. It started after upgrading the firmware in the bridge to version U1.2.6. Additionally, the new firmware version allows up to 5 simultaneous connections. According to the release notes, the stability has also been improved.

**Comment by michaelarnauts** [comment]
I also notice this since I updated the app (and that updated the firmware). I'll probably need to filter out those "bad" values somehow.

**Comment by roofburner** [comment]
Same issue here. Yesterday I upgraded my ComfoConnect. Since then I see the same behaviour as described.

It would be great to have this fixed!

Thanks for the analyse/fix.

![Capture](https://user-images.githubusercontent.com/360846/133423458-3c74da64-ad8c-4e41-9ea8-d632a7f71c08.JPG)

**Comment by xrado** [comment]
any plans for a new release with this fix?

**Comment by hanjo** [comment]
Hi,
this is related to the DHCP lease time. The new firmware seems to be closing the connections whenever it receives a new lease from the DHCP. So for example: If you've set the DHCP lease time to 60 minutes, the device will request a new IP every 30 minutes and thus you will see a zero-value in your graph every 30 minutes. Try to increase the lease time to something bigger such as a day. You should be seeing less of the zero values.
I'm in contact with the vendor about this already, from my point of view this should be fixed in the firmware.
It would be good to cover this case in the code of pycomfoconnect as well, but I'm not sure where this could be done.

**Comment by xrado** [comment]
I have manually assigned IP so is not changing

**Comment by michaelarnauts** [comment]
@hanjo @beniwohli 

I'm really struggling to find a good solution here. We can't just ignore the first value if it's zero, since some sensors like `days to replace sensor` can report a valid 0 value, and when we ignore the first value, we won't get a second update, so the value will stay undefined forever.

I'm trying to find the actual cause of the bug, maybe waiting a bit before we register the sensors can help, but I can't reproduce the issue besides waiting a long time until it happens.

**Comment by roofburner** [comment]
I rely on the ComfoConnect values to control my ventilation. Since the firmware update I experienced problems. I finally ended using the commited code, combined with these "filtered" sensors. In the recorder, I excluded all ComfoAirQ sensors.
It may be temporary, but at least, this works for me. I hope this code helps some of you...

```
recorder:
  exclude:
    entities:
      - sensor.comfoairq_exhaust_humidity
      - sensor.comfoairq_inside_humidity
      - sensor.comfoairq_outside_humidity
      - sensor.comfoairq_supply_humidity
      - sensor.comfoairq_power_usage
      - sensor.comfoairq_supply_temperature
      - sensor.comfoairq_exhaust_temperature
      - sensor.comfoairq_supply_airflow
      - sensor.comfoairq_exhaust_airflow
      - sensor.comfoairq_outside_temperature
      - sensor.comfoairq_inside_temperature
      - sensor.comfoairq_exhaust_fan_speed
      - sensor.comfoairq_exhaust_fan_duty
      - sensor.comfoairq_supply_fan_speed
      - sensor.comfoairq_supply_fan_duty
      - sensor.comfoairq_days_to_replace_filter
      - sensor.comfoairq_bypass_state

sensor:
  - platform: filter
    name: "ComfoAirQ Supply temperature (filter)"
    entity_id: sensor.comfoairq_supply_temperature
    filters:
      - filter: outlier
        window_size: 4
        radius: 2.0
      - filter: lowpass
        time_constant: 10
      - filter: time_simple_moving_average
        window_size: "00:05"
        precision: 1
  - platform: filter
    name: "ComfoAirQ Exhaust temperature (filter)"
    entity_id: sensor.comfoairq_exhaust_temperature
    filters:
      - filter: outlier
        window_size: 4
        radius: 2.0
      - filter: lowpass
        time_constant: 10
      - filter: time_simple_moving_average
        window_size: "00:05"
        precision: 1
  - platform: filter
    entity_id: sensor.comfoairq_outside_temperature
    name: "ComfoAirQ Outside temperature (filter)"
    filters:
      - filter: outlier
        window_size: 4
        radius: 2.0
      - filter: lowpass
        time_constant: 10
      - filter: time_simple_moving_average
        window_size: "00:05"
        precision: 1
  - platform: filter
    name: "ComfoAirQ Inside temperature (filter)"
    entity_id: sensor.comfoairq_inside_temperature
    filters:
      - filter: outlier
        window_size: 4
        radius: 2.0
      - filter: lowpass
        time_constant: 10
      - filter: time_simple_moving_average
        window_size: "00:05"
        precision: 1
  - platform: filter
    name: "ComfoAirQ Exhaust humidity (filter)"
    entity_id: sensor.comfoairq_exhaust_humidity
    filters:
      - filter: outlier
        window_size: 4
        radius: 4
      - filter: lowpass
        time_constant: 10
      - filter: time_simple_moving_average
        window_size: "00:05"
        precision: 0
  - platform: filter
    name: "ComfoAirQ Inside humidity (filter)"
    entity_id: sensor.comfoairq_inside_humidity
    filters:
      - filter: outlier
        window_size: 4
        radius: 4
      - filter: lowpass
        time_constant: 10
      - filter: time_simple_moving_average
        window_size: "00:01"
        precision: 0
  - platform: filter
    name: "ComfoAirQ Outside humidity (filter)"
    entity_id: sensor.comfoairq_outside_humidity
    filters:
      - filter: outlier
        window_size: 4
        radius: 4
      - filter: lowpass
        time_constant: 10
      - filter: time_simple_moving_average
        window_size: "00:01"
        precision: 0
  - platform: filter
    name: "ComfoAirQ Supply humidity (filter)"
    entity_id: sensor.comfoairq_supply_humidity
    filters:
      - filter: outlier
        window_size: 4
        radius: 4
      - filter: lowpass
        time_constant: 10
      - filter: time_simple_moving_average
        window_size: "00:01"
        precision: 0
  - platform: filter
    name: "ComfoAirQ Bypass state (filter)"
    entity_id: sensor.comfoairq_bypass_state
    filters:
      - filter: outlier
        window_size: 4
        radius: 100
        precision: 0
  - platform: filter
    name: "ComfoAirQ Days to replace filter (filter)"
    entity_id: sensor.comfoairq_days_to_replace_filter
    filters:
      - filter: outlier
        window_size: 4
        radius: 2
        precision: 0
```
